import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { BarChart3, ChevronDown, CircleHelp, Database, FileSpreadsheet, FolderOpen, LayoutDashboard, LoaderCircle, Plus, Send, Sparkles, Upload, X } from 'lucide-react';
import { CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis, BarChart, Bar, LineChart, Line } from 'recharts';
import { api } from './api';
import type { Analysis, Dataset } from './types';

export default function App(){
 const qc=useQueryClient();const {data:projects=[],isLoading,error}=useQuery({queryKey:['projects'],queryFn:api.projects});const [active,setActive]=useState<Dataset|null>(null);const [question,setQuestion]=useState('');const [conversation,setConversation]=useState<string>();const [answer,setAnswer]=useState<Analysis|null>(null);const [busy,setBusy]=useState(false);const [notice,setNotice]=useState('');
 const create=useMutation({mutationFn:()=>api.createProject('Untitled project'),onSuccess:()=>qc.invalidateQueries({queryKey:['projects']})});
 const upload=useMutation({mutationFn:({projectId,file}:{projectId:string;file:File})=>api.upload(projectId,file),onSuccess:d=>{qc.invalidateQueries({queryKey:['projects']});setActive(d);setAnswer(null);setConversation(undefined);setNotice('Dataset profiled and ready to explore.')},onError:e=>setNotice(e.message)});
 async function submit(q=question){if(!active||!q.trim())return;setQuestion(q);setBusy(true);setNotice('');try{const a=await api.ask(active.id,q,conversation);setAnswer(a);setConversation(a.conversation_id);setQuestion('')}catch(e){setNotice(e instanceof Error?e.message:'Analysis failed')}finally{setBusy(false)}}
 const fileInput=<input type="file" accept=".csv,.xlsx" className="hidden" onChange={e=>{const file=e.target.files?.[0];if(file){const project=projects[0];if(project)upload.mutate({projectId:project.id,file});else create.mutate(undefined,{onSuccess:p=>upload.mutate({projectId:p.id,file})})}e.currentTarget.value=''}}/>;
 return <div className="app-shell"><aside className="sidebar"><div className="brand"><span className="brand-mark"><BarChart3 size={18}/></span><span>datawise<span className="brand-dot">.</span></span></div><div className="workspace-switch"><span className="workspace-avatar">M</span><span className="workspace-name">My workspace<small>Free plan</small></span><ChevronDown size={15}/></div><div className="nav-label">WORKSPACE</div><nav><a className="nav-item active"><LayoutDashboard size={17}/>Overview</a><a className="nav-item"><FolderOpen size={17}/>Projects</a><a className="nav-item"><Database size={17}/>Datasets</a></nav><div className="nav-label recent-label">RECENT PROJECTS</div><div className="project-nav">{projects.map(p=><button key={p.id} className="nav-item" onClick={()=>p.datasets.length&&setActive(p.datasets[0])}><span className="project-dot"/>{p.name}</button>)}</div><button className="new-project" onClick={()=>create.mutate()}><Plus size={16}/>New project</button><div className="sidebar-bottom"><a className="nav-item"><CircleHelp size={17}/>Help center</a><div className="profile"><span className="avatar">MC</span><span>Mukul Chauhan<small>Personal workspace</small></span><ChevronDown size={15}/></div></div></aside>
 <main className="main"><header className="topbar"><div className="breadcrumbs"><span>Workspace</span><span className="crumb-sep">/</span><b>Overview</b></div><div className="top-right"><span className="connection"><i/> API connected</span><button className="help-button"><CircleHelp size={16}/><span>Help</span></button></div></header>
 <div className="content"><div className="welcome-row"><div><div className="eyebrow"><Sparkles size={14}/>YOUR ANALYTICS WORKSPACE</div><h1>Good morning, Mukul <span>✳</span></h1><p>Turn your data into decisions. What would you like to explore today?</p></div><button className="button-primary" onClick={()=>create.mutate()}><Plus size={17}/>New project</button></div>
 <section className="hero-card"><div className="hero-copy"><div className="hero-kicker">A LITTLE CLARITY GOES A LONG WAY</div><h2>Your data has a story.<br/><em>Let’s find it.</em></h2><p>Upload a dataset and ask questions in plain English.<br/>Your analyst is ready when you are.</p><label className="button-light"><Upload size={16}/>{upload.isPending?'Uploading…':'Upload a dataset'}{fileInput}</label><div className="file-note"><span>CSV</span><span>XLSX</span><b>Up to 25 MB</b></div></div><div className="hero-art"><div className="art-glow"/><div className="floating-tag tag-one"><span className="tag-icon mint">↗</span><span>Revenue trend<small>+18.4% this month</small></span></div><div className="chart-card"><div className="chart-card-top"><span>Monthly revenue</span><b>Last 6 months⌄</b></div><div className="mini-bars">{[35,49,43,64,55,79,67,92,72,84,65,100].map((v,i)=><i key={i} style={{height:`${v}%`,opacity:.38+i*.047}}/>)}</div><div className="chart-labels"><span>JAN</span><span>MAR</span><span>MAY</span><span>JUL</span></div></div><div className="floating-tag tag-two"><span className="tag-icon purple">✦</span><span>Insight found<small>3 patterns worth a look</small></span></div><div className="art-star">✳</div></div></section>
 <div className="section-heading"><div><h3>{active?'Dataset overview':'Your workspace'}</h3><p>{active?'A quick look at your data, before the questions begin.':'Everything you need to start exploring your data.'}</p></div>{active&&<button className="text-button" onClick={()=>setActive(null)}>Clear selection <X size={14}/></button>}</div>
 {notice&&<div className="notice" role="alert">{notice}<button onClick={()=>setNotice('')} aria-label="Dismiss"><X size={15}/></button></div>}
 {active?<><section className="stats-grid"><Stat label="Total rows" value={active.profile.row_count.toLocaleString()} icon="↕"/><Stat label="Columns" value={active.profile.column_count} icon="▤"/><Stat label="Missing values" value={active.profile.missing_cells} icon="◌"/><Stat label="Duplicate rows" value={active.profile.duplicate_rows} icon="⧉"/></section><div className="workspace-grid"><section className="panel dataset-panel"><div className="panel-head"><div><span className="file-badge"><FileSpreadsheet size={17}/></span><span className="panel-title">{active.filename}<small>Uploaded dataset</small></span></div><span className="status-pill"><i/>Ready</span></div><div className="column-list"><div className="column-head"><span>Column</span><span>Type</span><span>Missing</span></div>{active.profile.columns.map(c=><div className="column-row" key={c.name}><b>{c.name}</b><span className="type-pill">{c.semantic_type}</span><span>{c.null_percentage}%</span></div>)}</div></section><section className="panel ask-panel"><div className="ask-head"><span className="ai-badge"><Sparkles size={16}/></span><div><b>Ask your data</b><small>Natural language analysis</small></div><span className="mock-badge">AI READY</span></div><div className="suggestions"><span>Try asking</span>{['What are the top 5 categories by revenue?','Which columns have missing values?','How many rows are in the dataset?'].map(s=><button key={s} onClick={()=>submit(s)}>{s}<span>↗</span></button>)}</div><form className="question-box" onSubmit={e=>{e.preventDefault();submit()}}><textarea value={question} onChange={e=>setQuestion(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();submit()}}} placeholder="Ask a question about your data…"/><div className="question-actions"><small>↵ Enter to send</small><button disabled={busy||!question.trim()} aria-label="Send question">{busy?<LoaderCircle size={17} className="spin"/>:<Send size={16}/>}</button></div></form></section></div>
 {answer&&<section className="panel result-panel"><div className="result-head"><span className="ai-badge"><Sparkles size={16}/></span><div><b>Analysis</b><small>{answer.analysis_type.replace('_',' ')} · Verified against your dataset</small></div></div><p className="answer-text">{answer.answer}</p>{answer.visualization&&<div className="chart-wrap"><h4>{answer.visualization.title}</h4><ResponsiveContainer width="100%" height={260}>{answer.visualization.type==='line'?<LineChart data={answer.visualization.data}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey={answer.visualization.x}/><YAxis/><Tooltip/><Line dataKey={answer.visualization.y} stroke="#28745a" strokeWidth={3}/></LineChart>:<BarChart data={answer.visualization.data}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey={answer.visualization.x}/><YAxis/><Tooltip/><Bar dataKey={answer.visualization.y} fill="#28745a" radius={[5,5,0,0]}/></BarChart>}</ResponsiveContainer></div>}{answer.code&&<details className="code-details"><summary>View analysis code</summary><pre>{answer.code}</pre></details>}</section>}
 <section className="panel preview-panel"><div className="preview-head"><div><b>Data preview</b><small>First {active.profile.preview.length} rows</small></div><span>{active.profile.memory_bytes.toLocaleString()} bytes in memory</span></div><div className="table-scroll"><table><thead><tr>{active.profile.columns.map(c=><th key={c.name}>{c.name}</th>)}</tr></thead><tbody>{active.profile.preview.map((row,i)=><tr key={i}>{active.profile.columns.map(c=><td key={c.name}>{String(row[c.name]??'—')}</td>)}</tr>)}</tbody></table></div></section></>:<><section className="stats-grid"><Stat label="Active projects" value={projects.length} icon="▦"/><Stat label="Datasets" value={projects.reduce((a,p)=>a+p.datasets.length,0)} icon="▤"/><Stat label="Analysis sessions" value="—" icon="✳"/><Stat label="AI provider" value="Mock" icon="⌘"/></section><div className="workspace-grid"><section className="panel recent-panel"><div className="panel-head"><div><b>Recent projects</b><small>Your latest workspaces</small></div><button className="text-button">View all →</button></div>{isLoading?<div className="empty-state">Loading workspace…</div>:error?<div className="empty-state">Could not reach the API. Start the backend and refresh.</div>:projects.length?projects.map(p=><div className="recent-item" key={p.id}><span className="folder-icon"><FolderOpen size={17}/></span><span><b>{p.name}</b><small>{p.datasets.length} datasets · Updated just now</small></span><button onClick={()=>p.datasets[0]&&setActive(p.datasets[0])}>Open project →</button></div>):<div className="empty-state"><span className="empty-icon"><Database size={20}/></span><b>A fresh start</b><span>Create a project, then upload your first dataset.</span><button onClick={()=>create.mutate()}>Create your first project</button></div>}</section><section className="panel quick-panel"><div className="quick-icon"><Sparkles size={17}/></div><h3>From raw data<br/>to real answers.</h3><p>Just ask a question. Your data analyst handles the calculations, then brings the answer back with a clear chart.</p><div className="quick-example"><span>✦</span> “Which region had the most sales?”</div><div className="quick-example"><span>✦</span> “Plot monthly revenue”</div></section></div></>}
 <footer>Thoughtful analysis starts with good questions. <span>Built for curious minds <b>✳</b></span></footer></div></main></div>
}
function Stat({label,value,icon}:{label:string;value:string|number;icon:string}){return <div className="stat-card"><span className="stat-icon">{icon}</span><div><small>{label}</small><b>{value}</b></div><span className="stat-spark">↗</span></div>}
